FROM node:22-alpine AS build
WORKDIR /app

COPY package.json ./package.json
RUN npm install

COPY tsconfig.json ./tsconfig.json
COPY src ./src
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app

COPY package.json ./package.json
RUN npm install --omit=dev

COPY --from=build /app/dist ./dist
COPY --from=build /app/src/db/migrations ./dist/db/migrations
COPY --from=build /app/src/db/seeds ./dist/db/seeds

EXPOSE 4000
CMD ["npm", "run", "start:container"]
